// Every string of the page that a person reads, in English (`en`) and Korean (`ko`).
// `{name}` marks a value that the page fills in. Language names are written in their own
// language in both objects.

const en = {
  page_title: 'NMT Code',
  app_name: 'NMT Code',
  language_en: 'English',
  language_ko: '한국어',
  views: 'View',
  tab_read: 'Read',
  tab_make: 'Make',

  read_heading: 'Read a code',
  read_camera_start: 'Start camera',
  read_camera_stop: 'Stop camera',
  read_file_choose: 'Choose an image',
  read_video_label: 'Camera preview',
  read_status_starting: 'Starting the camera…',
  read_status_scanning: 'Point the camera at an NMT Code.',
  read_status_seen: 'A code is in view but could not be read yet ({name}). Hold the camera steady.',
  read_status_file: 'Reading the image…',
  read_none_in_file: 'No NMT Code was found in this image.',
  read_image_error: 'This image could not be opened.',
  camera_error_denied: "The camera was not allowed. Allow it in the browser's site settings, or choose an image.",
  camera_error_missing: 'No camera was found. Choose an image instead.',
  camera_error_insecure: 'The camera works only on https:// or localhost pages. Choose an image instead.',
  camera_error_other: 'The camera could not start. Choose an image instead.',
  engine_error: 'NMT Code could not start in this browser.',
  results_heading: 'Result',
  result_symbol: 'Code {n}',
  result_size: '{width} × {height} modules, error correction level {level}',

  record_text: 'Text',
  record_json: 'JSON',
  record_url: 'Link',
  record_file: 'File',
  record_psbt: 'PSBT file (Bitcoin transaction)',
  record_bytes: 'Bytes',
  record_unknown: 'Unknown content',
  record_unknown_detail: 'Content type {type}, which this reader does not know.',
  record_length: '{length} bytes',
  notice_not_utf8: 'This value is not valid UTF-8 text, so it is shown as bytes.',
  notice_not_psbt: 'This value does not start like a PSBT, so it is shown as a file.',
  text_truncated: 'Showing the first {shown} of {total} characters.',
  bytes_truncated: 'Showing the first {shown} of {total} bytes.',
  text_show_all: 'Show all',
  save_as_file: 'Save as a file',

  url_host: 'Host',
  url_alabel: 'Host in ASCII (A-label)',
  url_userinfo: 'This link has a user name or password before “@”. It opens {host}, not the name before “@”.',
  url_http: 'This link uses http: the connection is not encrypted.',
  url_invalid: 'This is not a valid web address. It is shown as text and cannot be opened.',
  url_never: 'Links that start with “{scheme}:” are never opened here.',
  url_show_all_to_open: 'Show the whole link to open it.',
  url_open: 'Open link',
  confirm_mailto: 'Open an email app to write to this address?',
  confirm_tel: 'Open the phone app to call this number?',
  confirm_sms: 'Open a messaging app to text this number?',
  confirm_geo: 'Open this place in a map app?',
  confirm_scheme: 'This link starts with “{scheme}:”. It opens in another app on this device, if one is installed. Open it?',
  confirm_continue: 'Open',
  confirm_cancel: 'Cancel',

  file_name: 'Name',
  file_name_none: 'The code gives no usable name. It is saved as {name}.',
  file_extension: 'Extension',
  file_extension_none: 'none',
  file_size: 'Size',
  file_save: 'Save file',

  error_unknown: 'The code could not be read.',
  err_E_NESTED_SYMBOL: 'One code lies inside another, so neither is shown.',
  err_E_FORMAT_UNREADABLE: 'The size and settings of the code could not be read.',
  err_E_FORMAT_CONFLICT: 'The two copies of the code settings disagree.',
  err_E_FORMAT_VERSION: 'This code uses a newer format. A newer reader is needed.',
  err_E_SIZE_LIMIT: 'This code is larger than this reader accepts.',
  err_E_ECC_FAILED: 'Too much of the code is damaged or unclear to correct.',
  err_E_COLOUR_AMBIGUOUS: 'Too many modules have colours outside the palette of the code.',
  err_E_LENGTH_FIELD: 'The content length in the code is damaged.',
  err_E_CRC_MISMATCH: 'The check value does not match: the code is damaged or was read wrongly.',
  err_E_CONTAINER_VERSION: 'This code uses a newer content format. A newer reader is needed.',
  err_E_TILE_RESERVED_BITS: 'This transfer code breaks the NMT Code specification.',
  err_E_TRANSFER_UNSUPPORTED: 'This code is part of a file transfer over several codes, which this reader cannot receive.',
  err_E_FORMAT_ECHO: 'The code settings and the content disagree. The code breaks the NMT Code specification.',
  err_E_COLOUR_FLAG: 'The code says it has colour content but is black and white. It breaks the NMT Code specification.',
  err_E_LEB128: 'A number in the code is written wrongly. The code breaks the NMT Code specification.',
  err_E_CODEC_ESCAPE: 'The code names its compression wrongly. It breaks the NMT Code specification.',
  err_E_UNSUPPORTED_CODEC: 'This code uses a compression method that this reader does not know.',
  err_E_UNKNOWN_DICTIONARY: 'This code needs a compression dictionary that this reader does not have.',
  err_E_DICTIONARY_MISMATCH: 'The dictionary does not fit the compression method. The code breaks the NMT Code specification.',
  err_E_HASH_ID_INVALID: 'The code names an invalid check method. It breaks the NMT Code specification.',
  err_E_UNKNOWN_HASH: 'This code uses a check method that this reader does not know.',
  err_E_HEADER_OVERRUN: 'The header runs past the content. The code breaks the NMT Code specification.',
  err_E_TOO_LARGE: 'The content is larger than this reader accepts.',
  err_E_MALFORMED: 'The content cannot be unpacked. The code breaks the NMT Code specification.',
  err_E_RECORD_LIST: 'The list of items in the code is broken. It breaks the NMT Code specification.',
  err_E_ACTION_RULE: 'The code holds more than one link, or a link in the wrong place. It breaks the NMT Code specification.',
  err_E_DIGEST_MISMATCH: 'The colour content does not match the digest of the code, so nothing is shown.',
  err_E_EXTENSION_UNREAD: 'This code holds more content in colour, which this reader cannot read. Only the black-and-white part is shown.',
  err_E_BOOTSTRAP_MISMATCH: 'The QR Code beside this code does not link to NMT Code.',

  make_heading: 'Make a code',
  make_kind: 'Content',
  kind_text: 'Text',
  kind_url: 'Link',
  kind_file: 'File',
  make_text_label: 'Text',
  make_url_label: 'Web address',
  make_url_placeholder: 'https://example.com',
  make_url_invalid: 'This is not a valid web address. Readers show it as text and do not offer to open it.',
  make_file_label: 'File',
  make_file_choose: 'Choose a file',
  make_file_chosen: '{name}, {size} bytes',
  make_file_none: 'No file chosen.',
  make_file_too_large: 'This file is larger than 1 MiB, the most that one code holds.',
  make_file_read_error: 'The file could not be read.',
  make_level: 'Error correction',
  level_0: '0 (restores about 7.5%)',
  level_1: '1 (restores about 15%)',
  level_2: '2 (restores about 25%)',
  level_3: '3 (restores about 30%)',
  make_module_size: 'Module size in pixels',
  make_qr: 'Add a QR Code that links to NMT Code',
  make_qr_hint: 'Phones that read only QR Codes get a link to the NMT Code project. The image gets larger.',
  make_empty_text: 'Type text to make a code.',
  make_empty_url: 'Type a web address to make a code.',
  make_empty_file: 'Choose a file to make a code.',
  make_info: '{width} × {height} modules · level {level} · {used} of {capacity} bytes used',
  make_image_size: 'Image: {width} × {height} pixels',
  make_preview_label: 'Preview of the code',
  download_png: 'Download PNG',
  download_svg: 'Download SVG',
  make_error_unknown_kind: 'This kind of content is not supported.',
  make_error_not_utf8: 'The text is not valid UTF-8.',
  make_error_invalid_level: 'The error correction level must be 0 to 3.',
  make_error_invalid_module_size: 'The module size is out of range.',
  make_error_too_large: 'The content is too large for one code. One code holds at most 1 MiB.',
  make_error_no_size: 'No code size holds this content at this level. Choose a lower level.',
  make_error_image_too_large: 'The image would be too large. Choose a smaller module size.',
  make_error_internal: 'The code could not be made because of an error in this page.',

  footer_version: 'Version {version}',
  footer_source: 'Source code on GitHub',
  footer_licenses: 'Third-party licenses',
  footer_trademark: 'QR Code is a registered trademark of DENSO WAVE INCORPORATED.',
};

const ko = {
  page_title: 'NMT Code',
  app_name: 'NMT Code',
  language_en: 'English',
  language_ko: '한국어',
  views: '보기',
  tab_read: '읽기',
  tab_make: '만들기',
  read_heading: '코드 읽기',
  read_camera_start: '카메라 켜기',
  read_camera_stop: '카메라 끄기',
  read_file_choose: '이미지 고르기',
  read_video_label: '카메라 미리보기',
  read_status_starting: '카메라를 켜는 중입니다…',
  read_status_scanning: '카메라를 NMT Code에 비추십시오.',
  read_status_seen: '코드가 보이지만 아직 읽지 못했습니다({name}). 카메라가 흔들리지 않게 잡으십시오.',
  read_status_file: '이미지를 읽는 중입니다…',
  read_none_in_file: '이 이미지에서 NMT Code를 찾지 못했습니다.',
  read_image_error: '이 이미지를 열 수 없습니다.',
  camera_error_denied: '카메라 권한이 없습니다. 브라우저의 사이트 설정에서 카메라를 허용하거나 이미지를 고르십시오.',
  camera_error_missing: '카메라를 찾지 못했습니다. 이미지를 고르십시오.',
  camera_error_insecure: '카메라는 https:// 주소나 localhost 페이지에서만 켜집니다. 이미지를 고르십시오.',
  camera_error_other: '카메라를 켜지 못했습니다. 이미지를 고르십시오.',
  engine_error: '이 브라우저에서는 NMT Code를 실행할 수 없습니다.',
  results_heading: '결과',
  result_symbol: '코드 {n}',
  result_size: '{width} × {height} 모듈, 오류 정정 수준 {level}',
  record_text: '텍스트',
  record_json: 'JSON',
  record_url: '링크',
  record_file: '파일',
  record_psbt: 'PSBT 파일(비트코인 거래)',
  record_bytes: '바이트',
  record_unknown: '알 수 없는 내용',
  record_unknown_detail: '내용 종류 {type}입니다. 이 리더가 모르는 종류입니다.',
  record_length: '{length}바이트',
  notice_not_utf8: '올바른 UTF-8 텍스트가 아니어서 바이트로 보여 줍니다.',
  notice_not_psbt: 'PSBT로 시작하지 않아서 파일로 보여 줍니다.',
  text_truncated: '전체 {total}자 중 처음 {shown}자를 보여 줍니다.',
  bytes_truncated: '전체 {total}바이트 중 처음 {shown}바이트를 보여 줍니다.',
  text_show_all: '전부 보기',
  save_as_file: '파일로 저장',
  url_host: '호스트',
  url_alabel: 'ASCII로 쓴 호스트(A-label)',
  url_userinfo: '이 링크에는 「@」 앞에 사용자 이름이나 비밀번호가 있습니다. 열리는 곳은 「@」 앞의 이름이 아니라 {host}입니다.',
  url_http: '이 링크는 http를 씁니다. 연결이 암호화되지 않습니다.',
  url_invalid: '올바른 웹 주소가 아닙니다. 텍스트로만 보여 주고 열 수 없습니다.',
  url_never: '「{scheme}:」로 시작하는 링크는 여기서 열지 않습니다.',
  url_show_all_to_open: '열려면 링크를 전부 펼치십시오.',
  url_open: '링크 열기',
  confirm_mailto: '이메일 앱을 열어 이 주소로 메일을 쓰시겠습니까?',
  confirm_tel: '전화 앱을 열어 이 번호로 전화하시겠습니까?',
  confirm_sms: '메시지 앱을 열어 이 번호로 문자를 보내시겠습니까?',
  confirm_geo: '이 위치를 지도 앱에서 여시겠습니까?',
  confirm_scheme: '이 링크는 「{scheme}:」로 시작합니다. 이 기기에 그 앱이 있으면 그 앱에서 열립니다. 여시겠습니까?',
  confirm_continue: '열기',
  confirm_cancel: '취소',
  file_name: '이름',
  file_name_none: '코드에 쓸 수 있는 파일 이름이 없습니다. {name} 이름으로 저장합니다.',
  file_extension: '확장자',
  file_extension_none: '없음',
  file_size: '크기',
  file_save: '파일 저장',
  error_unknown: '코드를 읽지 못했습니다.',
  err_E_NESTED_SYMBOL: '코드 안에 다른 코드가 들어 있어 어느 쪽도 보여 주지 않습니다.',
  err_E_FORMAT_UNREADABLE: '코드의 크기와 설정을 읽지 못했습니다.',
  err_E_FORMAT_CONFLICT: '코드 설정의 두 사본이 서로 다릅니다.',
  err_E_FORMAT_VERSION: '더 새로운 형식의 코드입니다. 새 버전의 리더가 필요합니다.',
  err_E_SIZE_LIMIT: '이 리더가 받는 크기보다 큰 코드입니다.',
  err_E_ECC_FAILED: '코드가 너무 많이 손상됐거나 흐려서 바로잡지 못했습니다.',
  err_E_COLOUR_AMBIGUOUS: '코드의 색 목록에 없는 색을 띤 모듈이 너무 많습니다.',
  err_E_LENGTH_FIELD: '코드에 적힌 내용 길이가 손상됐습니다.',
  err_E_CRC_MISMATCH: '검사값이 맞지 않습니다. 코드가 손상됐거나 잘못 읽혔습니다.',
  err_E_CONTAINER_VERSION: '더 새로운 내용 형식의 코드입니다. 새 버전의 리더가 필요합니다.',
  err_E_TILE_RESERVED_BITS: '이 전송 코드는 NMT Code 명세를 어깁니다.',
  err_E_TRANSFER_UNSUPPORTED: '여러 장의 코드로 파일을 보내는 전송의 한 장입니다. 이 리더는 전송을 받지 못합니다.',
  err_E_FORMAT_ECHO: '코드 설정과 내용이 서로 다릅니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_COLOUR_FLAG: '흑백 코드인데 색 내용이 있다고 적혀 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_LEB128: '코드 안의 숫자가 잘못 적혀 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_CODEC_ESCAPE: '압축 방식이 잘못 적혀 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_UNSUPPORTED_CODEC: '이 리더가 모르는 압축 방식을 쓴 코드입니다.',
  err_E_UNKNOWN_DICTIONARY: '이 리더에 없는 압축 사전이 필요한 코드입니다.',
  err_E_DICTIONARY_MISMATCH: '압축 방식에 맞지 않는 사전이 적혀 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_HASH_ID_INVALID: '검사 방식이 잘못 적혀 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_UNKNOWN_HASH: '이 리더가 모르는 검사 방식을 쓴 코드입니다.',
  err_E_HEADER_OVERRUN: '머리 정보가 내용보다 깁니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_TOO_LARGE: '이 리더가 받는 크기보다 큰 내용입니다.',
  err_E_MALFORMED: '내용의 압축을 풀 수 없습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_RECORD_LIST: '코드 안의 항목 목록이 깨져 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_ACTION_RULE: '링크가 둘 이상이거나, 링크가 올 수 없는 자리에 있습니다. NMT Code 명세를 어기는 코드입니다.',
  err_E_DIGEST_MISMATCH: '색 내용이 코드의 요약값과 맞지 않아 아무것도 보여 주지 않습니다.',
  err_E_EXTENSION_UNREAD: '이 코드에는 색으로 담은 내용이 더 있지만 이 리더는 읽지 못합니다. 흑백 부분만 보여 줍니다.',
  err_E_BOOTSTRAP_MISMATCH: '이 코드 옆의 QR 코드가 NMT Code로 가는 링크가 아닙니다.',
  make_heading: '코드 만들기',
  make_kind: '내용',
  kind_text: '텍스트',
  kind_url: '링크',
  kind_file: '파일',
  make_text_label: '텍스트',
  make_url_label: '웹 주소',
  make_url_placeholder: 'https://example.com',
  make_url_invalid: '올바른 웹 주소가 아닙니다. 리더는 이것을 텍스트로 보여 주고 열지 않습니다.',
  make_file_label: '파일',
  make_file_choose: '파일 고르기',
  make_file_chosen: '{name}, {size}바이트',
  make_file_none: '고른 파일이 없습니다.',
  make_file_too_large: '1 MiB보다 큰 파일입니다. 코드 하나에는 1 MiB까지 담깁니다.',
  make_file_read_error: '파일을 읽지 못했습니다.',
  make_level: '오류 정정',
  level_0: '0 (약 7.5% 복구)',
  level_1: '1 (약 15% 복구)',
  level_2: '2 (약 25% 복구)',
  level_3: '3 (약 30% 복구)',
  make_module_size: '모듈 크기(픽셀)',
  make_qr: 'NMT Code로 가는 QR 코드 붙이기',
  make_qr_hint: 'QR 코드만 읽는 폰은 NMT Code 프로젝트로 가는 링크를 얻습니다. 이미지가 커집니다.',
  make_empty_text: '텍스트를 입력하면 코드가 만들어집니다.',
  make_empty_url: '웹 주소를 입력하면 코드가 만들어집니다.',
  make_empty_file: '파일을 고르면 코드가 만들어집니다.',
  make_info: '{width} × {height} 모듈 · 수준 {level} · {capacity}바이트 중 {used}바이트 사용',
  make_image_size: '이미지: {width} × {height} 픽셀',
  make_preview_label: '코드 미리보기',
  download_png: 'PNG 내려받기',
  download_svg: 'SVG 내려받기',
  make_error_unknown_kind: '지원하지 않는 내용 종류입니다.',
  make_error_not_utf8: '올바른 UTF-8 텍스트가 아닙니다.',
  make_error_invalid_level: '오류 정정 수준은 0부터 3까지입니다.',
  make_error_invalid_module_size: '모듈 크기가 허용 범위 밖입니다.',
  make_error_too_large: '코드 하나에 담기에는 너무 큰 내용입니다. 코드 하나에는 1 MiB까지 담깁니다.',
  make_error_no_size: '이 수준에서는 이 내용이 들어가는 크기가 없습니다. 더 낮은 수준을 고르십시오.',
  make_error_image_too_large: '이미지가 너무 커집니다. 모듈 크기를 줄이십시오.',
  make_error_internal: '이 페이지의 오류로 코드를 만들지 못했습니다.',
  footer_version: '버전 {version}',
  footer_source: 'GitHub의 소스 코드',
  footer_licenses: '제3자 라이선스',
  footer_trademark: 'QR Code는 DENSO WAVE INCORPORATED의 등록 상표입니다.',
};

export const STRINGS = Object.freeze({ en: Object.freeze(en), ko: Object.freeze(ko) });
